### ISSUE TITLE
What is the best way to follow this repository?

### ISSUE THREAD

**Issue by rauschma** [tc39/notes#132]
At the moment, watching the repository produces a lot of notifications.

What would be the best way to follow this repository? Maybe one release per meeting?

**Comment by jridgewell** [comment]
That's a great suggestion.

![GitHub Repo Notification Settings](https://user-images.githubusercontent.com/112982/119536012-9df75000-bd56-11eb-82eb-5580e056a632.png)
![GitHub Repo Notification Settings - Customize Notifications](https://user-images.githubusercontent.com/112982/119536022-9fc11380-bd56-11eb-8507-c000d106e496.png)

**Comment by ljharb** [comment]
Confining it to "pull requests" would help as-is; if we're good about making a release for each meeting then this seems like the best suggestion.

**Comment by ljharb** [comment]
I think the best solution here is a Github Action, that only runs on the default branch, that creates a Github Release for any folder in `meetings` that doesn't have already have a release.

That way, it will automatically backfill, and future notes PRs will create a single new release, and folks can follow only releases.

**Comment by ctcpip** [comment]
[release](https://github.com/tc39/notes/releases/tag/2023-07) created via [workflow](https://github.com/tc39/notes/actions/runs/6318495144/job/17157596168)
