### ISSUE TITLE
Any notes about the ongoing tc39 meeting?

### ISSUE THREAD

**Issue by nojvek** [tc39/notes#18]
Just wanna know the status is .? And ?? Operator mostly.

**Comment by GaryGSC** [comment]
**?.**: https://github.com/tc39/proposals/commit/34c4f061bc4d1ca143621aaec78fa7f8585241a7

**??**: https://github.com/tc39/proposals/commit/6020b6f383152f92a491f9e2cc365cf6e2ef17d5

The notes won't be available until after delegates have had a chance to review them.

**Comment by nojvek** [comment]
oooooooo Awesome.

Gonna close this.
