### ISSUE TITLE
Gap between meeting and note publish

### ISSUE THREAD

**Issue by Jxck** [tc39/notes#202]
Hi Team

Firstly, thank you so much for publish meeting notes, It's so valuable for catching up current discussion in tc39.
I think it takes almost 1 month between meeting and note publish, so others who wasn't there could not catching up discussion util it published.
I understand it requires long time for editing note in markdown, so I wonder why don't taking minutes over google docs / ether pad etc which can be shared in realtime ? Some working group in IETF utilize ether pad here and it's so helpful.
I don't know who / how taking minutes in meeting but it would be nice if folks could see the minutes earlier even if it's not well formatted.

Thanks

**Comment by ljharb** [comment]
We intentionally don’t share them until they’ve been edited, since real-time notes are often inaccurate and can easily be misinterpreted.

Typically the gap is 2 weeks, but at times the (volunteer) chairs have other conflicts. The last meeting’s notes are indeed overdue to be published.
