### ISSUE TITLE
Introduce tracking of member organizations?

### ISSUE THREAD

**Issue by codehag** [tc39/notes#36]
Should we be tracking who delegates are representing? This would help with identifying invited experts, and participating members for role call.

**Comment by michaelficarra** [comment]
If we want to start putting more structured info in there, I recommend switching to a CSV format. We do that for our CLA signatories at Shape, and GitHub provides a much better UI for it: https://github.com/shapesecurity/CLA/blob/master/CONTRIBUTORS.csv

**Comment by ctcpip** [comment]
closing as we now do this via GH teams.  feel free to reopen if I misunderstood.
